// Generated by CoffeeScript 1.6.2
(function() {
  var fs, http;

  http = require('http');

  fs = require('fs');

  http.createServer(function(req, res) {
    console.log('starting server...');
    return fs.readFile('index.html', function(err, content) {
      if (err) {
        throw err;
      }
      res.writeHead(200, {
        'Content-Type': 'text/html',
        'charset': 'utf-8'
      });
      return res.end(content);
    });
  }).listen(3000, 'localhost');

  console.log('listening...');

}).call(this);
